services:
  pr_manager:
    build: .
    container_name: pr_manager
    ports:
      - "8080:8080"
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_ADDRESS=postgres-db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_SSLMODE=disable
      - LISTEN_PORT=8080
    depends_on:
      postgres-db:
        condition: service_healthy
    restart: on-failure

  postgres-db:
    image: postgres:18.0-alpine3.22
    container_name: pr_manager_postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 3s
